### ISSUE TITLE
raise EnvironmentError( OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ./Language_files.

### ISSUE THREAD

**Issue by xiawei999000** [chaoyi-wu/RadFM#43]
Hello,
I run the code of inference with RadFM using H800 (80GB)

**Follow the steps:**
S1. Download [Model checkpoint](https://huggingface.co/chaoyi-wu/RadFM) or form [baiduyun](https://pan.baidu.com/s/1A-K5nXCbvWAVqvb6dLjYJg?pwd=q1eo) (No need for decompressing).

S2. Decompress the original zip file, you can get a pytorch_model.bin.

S3. put pytorch_model.bin under path Quick_demo/.

**and I get some errors:**
 
Setup tokenizer
Finish loading tokenizer
Setup demo case
Finish loading demo case
Setup Model
Traceback (most recent call last):
  File "/mnt/nfs_share/models_ckps/RadFM/Quick_demo/test.py", line 176, in <module>
    main()
  File "/mnt/nfs_share/models_ckps/RadFM/Quick_demo/test.py", line 138, in main
    model = MultiLLaMAForCausalLM(
  File "/mnt/nfs_share/models_ckps/RadFM/Quick_demo/Model/RadFM/multimodality_model.py", line 28, in __init__
    self.lang_model = LlamaForCausalLM.from_pretrained(
  File "/mnt/nfs_share/.conda/envs/RadFM/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2405, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ./Language_files.

**Comment by Dlocking** [comment]
Same question, and the version of transformers == 4.28.1. Have you solved the problem?

**Comment by xiawei999000** [comment]
not yet, please let me know if you find the solution.



---- Replied Message ----
| From | ***@***.***> |
| Date | 06/02/2025 20:29 |
| To | ***@***.***> |
| Cc | Wei ***@***.***>***@***.***> |
| Subject | Re: [chaoyi-wu/RadFM] raise EnvironmentError( OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ./Language_files. (Issue #43) |
Dlocking left a comment (chaoyi-wu/RadFM#43)

Same question, and the version of transformers == 4.28.1. Have you solved the problem?

**Comment by RobsoUganda** [comment]
It seems you have the similar problem i faced  and it was fixed in this issue https://github.com/chaoyi-wu/RadFM/issues/22

**Comment by Dlocking** [comment]
> It seems you have the similar problem i faced and it was fixed in this issue [#22](https://github.com/chaoyi-wu/RadFM/issues/22)

I have set the version of transformers == 4.28.1, but I still get the error. However, I haven't encountered the memory bug as you met. Besides the version of transformers, did you do anything else for solving the problem? Please help, thanks.

**Comment by Yue256** [comment]
> not yet, please let me know if you find the solution.
> […](#)

I mv the pytorch_model.bin to ./Language_files and change ckpt = torch.load('./Language_files/pytorch_model.bin').
Finally it works

**Comment by xiawei999000** [comment]
> > not yet, please let me know if you find the solution.
> > […](#)
> 
> I mv the pytorch_model.bin to ./Language_files and change ckpt = torch.load('./Language_files/pytorch_model.bin'). Finally it works

Thank you. It works.
